---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item. The playbook contains a list of
# plays, with each play being a dictionary
- name: "Creating a apache user and group on webservers"
  # Target: where our play will run and options it will run with
  hosts: webservers
  tasks:
    - name: create ansible group 
      group: name=apache state=present
      tags:
        - apache

    - name: create apache user
      user: name=apache group=apache 
      tags: 
        - apache
