---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item. The playbook contains a list of
# plays, with each play being a dictionary
- name: "Installing apache on webservers"
  # Target: where our play will run and options it will run with
  hosts: webservers
  tasks:
    # ensure apache is installed in redhat and centos platform distribution
    - name: ensure apache is at the latest version
      yum: name=httpd state=absent
      when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
      tags:
        - apache

    # ensure apache is installed in redhat and centos platform distribution
    - name: Install apache
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - apache2
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
      tags:
        - apache
    # restart apache in ubuntu or debian
    - name: restart apache
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags:
        - apache
    - name: ensure apache is running 
      service: name=httpd state=started enabled=yes
      tags:
        - apache
